apiVersion: v1
kind: Service
metadata:
  name: domain-name
  namespace: webmap
  labels:
    app: treetracker-web-map-client-next
  annotations:
    getambassador.io/config: 
      apiVersion: ambassador/v2
      kind: Mapping
      name: domain-name
      #host: next-map.treetracker.org
      prefix: /
      service: treetracker-web-map-client-next-ambassador-svc
      rewrite: /web-map-beta/
spec:
  type: ClusterIP
  selector:
    app: treetracker-web-map-client-next
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
