openapi: 3.0.0
info:
  title: web map api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/trees/{treeId}':
    parameters:
      - schema:
          type: string
        name: treeId
        in: path
        required: true
    get:
      summary: get tree info
      tags: []
      responses: {}
      operationId: get-trees-treeId
  /trees/featured:
    get:
      summary: get featured tree list
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tree'
      operationId: get-trees-featured
      description: this is some good trees bookmarked by admin
  /countries/leader:
    get:
      summary: leader board of country
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/country'
      operationId: get-countries-leader
      description: a board of leader country
components:
  schemas:
    tree:
      description: ''
      type: object
      properties:
        id:
          type: number
        photo_url:
          type: string
          minLength: 1
        verified:
          type: boolean
        token_id:
          type: string
          minLength: 1
        impact_manager_id:
          type: string
          minLength: 1
        impact_producer_id:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
        lat:
          type: number
        lon:
          type: number
        species:
          type: string
          minLength: 1
        planter_id:
          type: number
      required:
        - id
        - photo_url
        - verified
        - token_id
        - impact_manager_id
        - impact_producer_id
        - created_at
        - lat
        - lon
        - species
        - planter_id
      x-examples:
        example-tree:
          id: 933042
          photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.49.19_-4.881696978000001_38.37997515399998_47fc629b-27e9-4b58-b31a-3a35e5bbc3f0_IMG_20210518_121452_1024002290.jpg'
          verified: true
          token_id: d4bb294b-8c75-4e0f-af43-1cd9a35e1033
          impact_manager_id: 8599f832-145e-11ec-82a8-0242ac130003
          impact_producer_id: a0b6b70e-145e-11ec-82a8-0242ac130003
          created_at: '5/18/2021, 5:14:48 PM'
          lat: -4.881696978000001
          lon: 38.37997515399998
          species: Markhamia lutea
          planter_id: 5
          value:
            id: 933042
            photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.49.19_-4.881696978000001_38.37997515399998_47fc629b-27e9-4b58-b31a-3a35e5bbc3f0_IMG_20210518_121452_1024002290.jpg'
            verified: true
            token_id: d4bb294b-8c75-4e0f-af43-1cd9a35e1033
            impact_manager_id: 8599f832-145e-11ec-82a8-0242ac130003
            impact_producer_id: a0b6b70e-145e-11ec-82a8-0242ac130003
            created_at: '5/18/2021, 5:14:48 PM'
            lat: -4.881696978000001
            lon: 38.37997515399998
            species: Markhamia lutea
            planter_id: 5
      title: ''
    country:
      description: ''
      type: object
      properties:
        name:
          type: string
          minLength: 1
        planted:
          type: number
        id:
          type: string
          minLength: 1
        continent:
          type: string
          minLength: 1
      required:
        - name
        - planted
        - id
        - continent
      x-examples:
        example-country:
          name: Tanzania
          planted: 100000
          id: ef883620-15d8-11ec-9c2b-0242ac130003
          continent: Africa
          value:
            name: Tanzania
            planted: 100000
            id: ef883620-15d8-11ec-9c2b-0242ac130003
            continent: Africa
