apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: treetracker-web-map-client-be-api
  namespace: webmap
spec:
  prefix: /web-map-site/
  service: treetracker-web-map-client-ambassador-svc
  rewrite: /
  timeout_ms: 0
  cors:
    methods: GET, OPTIONS
    headers:
      - Content-Type
      - Authorization
