apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: treetracker-web-map-client-beta-be-api
  namespace: webmap
spec:
  prefix: /web-map-beta/
  service: treetracker-web-map-client-beta-ambassador-svc
  rewrite: /web-map-beta/
