# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API CI for New Pull Requests

on:
  pull_request:
    branches:
      - web-map-site

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install and cache NPM dependencies, run integration tests
      - name: Cypress E2E (Dev Server) 🧪
        uses: cypress-io/github-action@v2
        with:
          # run these before testing
          start: |
            npm run mock-server
            npm run dev
          # wait for server to be ready
          wait-on: 'http://localhost:3000'

      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npx cypress run-ct

      - name: Jest Unit Tests 🧪
        run: npx jest --ci

      - name: ESLint
        run: npm run lint

      - name: Save screenshots
        # step runs even if other steps fail
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: client/cypress/screenshots

      - name: Save videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: client/cypress/videos
